"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 05:31:29.964378
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=40), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('assessment', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_decision_id'), 'ai_analyses', ['decision_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_mint'), 'ai_analyses', ['mint'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_versions',
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('execution_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=40), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_events_execution_id'), 'execution_events', ['execution_id'], unique=False)
    op.create_table('executions',
    sa.Column('execution_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('transaction_signature', sa.String(length=100), nullable=True),
    sa.Column('blockhash', sa.String(length=64), nullable=True),
    sa.Column('last_valid_block_height', sa.BigInteger(), nullable=True),
    sa.Column('slot', sa.BigInteger(), nullable=True),
    sa.Column('requested_amount', sa.BigInteger(), nullable=False),
    sa.Column('actual_in', sa.BigInteger(), nullable=False),
    sa.Column('actual_out', sa.BigInteger(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=False),
    sa.Column('actual_price', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('platform_fees', sa.BigInteger(), nullable=False),
    sa.Column('network_fees', sa.BigInteger(), nullable=False),
    sa.Column('priority_fee', sa.BigInteger(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('execution_id'),
    sa.UniqueConstraint('transaction_signature')
    )
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=40), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_decision_id'), 'features', ['decision_id'], unique=False)
    op.create_index(op.f('ix_features_mint'), 'features', ['mint'], unique=False)
    op.create_index(op.f('ix_features_t'), 'features', ['t'], unique=False)
    op.create_table('market_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=100), nullable=False),
    sa.Column('slot', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.Float(), nullable=False),
    sa.Column('chain_time', sa.Float(), nullable=False),
    sa.Column('venue', sa.String(length=16), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('sol_amount', sa.BigInteger(), nullable=False),
    sa.Column('token_amount', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature', 'seq', 'kind', name='uq_market_event')
    )
    op.create_index('ix_market_events_mint_t', 'market_events', ['mint', 'observed_at'], unique=False)
    op.create_index(op.f('ix_market_events_slot'), 'market_events', ['slot'], unique=False)
    op.create_index('ix_market_events_t', 'market_events', ['observed_at'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('venue', sa.String(length=16), nullable=True),
    sa.Column('price_lamports_per_token', sa.Float(), nullable=True),
    sa.Column('market_cap_sol', sa.Float(), nullable=True),
    sa.Column('liquidity_sol', sa.Float(), nullable=True),
    sa.Column('volume_sol_5m', sa.Float(), nullable=True),
    sa.Column('buys_5m', sa.Integer(), nullable=True),
    sa.Column('sells_5m', sa.Integer(), nullable=True),
    sa.Column('holders', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snap_mint_t', 'market_snapshots', ['mint', 't'], unique=False)
    op.create_table('operator_commands',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('processed_at', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_commands_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('command_id', sa.BigInteger(), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('execution_id', sa.String(length=40), nullable=False),
    sa.Column('decision_id', sa.String(length=40), nullable=True),
    sa.Column('position_id', sa.String(length=40), nullable=True),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('venue', sa.String(length=16), nullable=False),
    sa.Column('amount_in', sa.BigInteger(), nullable=False),
    sa.Column('min_out', sa.BigInteger(), nullable=False),
    sa.Column('expected_out', sa.BigInteger(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=False),
    sa.Column('spot_price', sa.Float(), nullable=False),
    sa.Column('expected_slippage', sa.Float(), nullable=False),
    sa.Column('priority_micro_lamports', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_orders_decision_id'), 'orders', ['decision_id'], unique=False)
    op.create_index(op.f('ix_orders_mint'), 'orders', ['mint'], unique=False)
    op.create_index(op.f('ix_orders_position_id'), 'orders', ['position_id'], unique=False)
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=False)
    op.create_table('outcome_samples',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('regime', sa.String(length=24), nullable=False),
    sa.Column('gross_return', sa.Float(), nullable=False),
    sa.Column('net_return', sa.Float(), nullable=False),
    sa.Column('hold_s', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('strategy_version', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_samples_source'), 'outcome_samples', ['source'], unique=False)
    op.create_index(op.f('ix_outcome_samples_strategy_version'), 'outcome_samples', ['strategy_version'], unique=False)
    op.create_index(op.f('ix_outcome_samples_t'), 'outcome_samples', ['t'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('equity_sol', sa.Float(), nullable=False),
    sa.Column('cash_sol', sa.Float(), nullable=False),
    sa.Column('realized_pnl_sol', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl_sol', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_session_id'), 'portfolio_snapshots', ['session_id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_t'), 'portfolio_snapshots', ['t'], unique=False)
    op.create_table('position_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.String(length=40), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('event', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_events_position_id'), 'position_events', ['position_id'], unique=False)
    op.create_table('positions',
    sa.Column('position_id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('opened_at', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_index(op.f('ix_positions_mint'), 'positions', ['mint'], unique=False)
    op.create_index(op.f('ix_positions_session_id'), 'positions', ['session_id'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_table('research_experiments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('data_range', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_experiments_name'), 'research_experiments', ['name'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_kind'), 'risk_events', ['kind'], unique=False)
    op.create_index(op.f('ix_risk_events_t'), 'risk_events', ['t'], unique=False)
    op.create_table('runtime_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('scores',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=40), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_decision_id'), 'scores', ['decision_id'], unique=False)
    op.create_index(op.f('ix_scores_mint'), 'scores', ['mint'], unique=False)
    op.create_index(op.f('ix_scores_t'), 'scores', ['t'], unique=False)
    op.create_table('signal_outcomes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=40), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=24), nullable=True),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_version', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_index(op.f('ix_signal_outcomes_mint'), 'signal_outcomes', ['mint'], unique=False)
    op.create_index(op.f('ix_signal_outcomes_t'), 'signal_outcomes', ['t'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=40), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=12), nullable=False),
    sa.Column('market_state', sa.String(length=32), nullable=True),
    sa.Column('regime', sa.String(length=24), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('ev', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sizing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('execution_estimate', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('gates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rejection_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('strategy_version', sa.String(length=40), nullable=False),
    sa.Column('feature_version', sa.String(length=40), nullable=False),
    sa.Column('configuration_version', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('ai_model', sa.String(length=64), nullable=False),
    sa.Column('versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_index(op.f('ix_signals_mint'), 'signals', ['mint'], unique=False)
    op.create_index(op.f('ix_signals_outcome'), 'signals', ['outcome'], unique=False)
    op.create_index(op.f('ix_signals_session_id'), 'signals', ['session_id'], unique=False)
    op.create_index(op.f('ix_signals_t'), 'signals', ['t'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('component', sa.String(length=40), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_t'), 'system_events', ['t'], unique=False)
    op.create_table('token_state_transitions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=False),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_state_transitions_mint'), 'token_state_transitions', ['mint'], unique=False)
    op.create_table('tokens',
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('market_state', sa.String(length=32), nullable=False),
    sa.Column('bonding_curve_address', sa.String(length=64), nullable=True),
    sa.Column('pool_address', sa.String(length=64), nullable=True),
    sa.Column('graduation_state', sa.String(length=16), nullable=False),
    sa.Column('first_seen_slot', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_slot', sa.BigInteger(), nullable=False),
    sa.Column('first_seen_at', sa.Float(), nullable=False),
    sa.Column('last_trade_at', sa.Float(), nullable=True),
    sa.Column('partial_history', sa.Boolean(), nullable=False),
    sa.Column('token_program', sa.String(length=64), nullable=True),
    sa.Column('quote_mint', sa.String(length=64), nullable=True),
    sa.Column('is_mayhem', sa.Boolean(), nullable=False),
    sa.Column('untradeable_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('mint')
    )
    op.create_index(op.f('ix_tokens_creator'), 'tokens', ['creator'], unique=False)
    op.create_index(op.f('ix_tokens_market_state'), 'tokens', ['market_state'], unique=False)
    op.create_index(op.f('ix_tokens_pool_address'), 'tokens', ['pool_address'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('opened_at', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.Float(), nullable=False),
    sa.Column('pnl_sol', sa.Float(), nullable=False),
    sa.Column('net_return', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(length=32), nullable=False),
    sa.Column('strategy_version', sa.String(length=40), nullable=False),
    sa.Column('configuration_version', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    op.create_index(op.f('ix_trades_closed_at'), 'trades', ['closed_at'], unique=False)
    op.create_index(op.f('ix_trades_mint'), 'trades', ['mint'], unique=False)
    op.create_index(op.f('ix_trades_session_id'), 'trades', ['session_id'], unique=False)
    op.create_table('wallet_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.String(length=64), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_events_wallet'), 'wallet_events', ['wallet'], unique=False)
    op.create_table('wallets',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_smart', sa.Boolean(), nullable=False),
    sa.Column('cluster', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_index(op.f('ix_wallet_events_wallet'), table_name='wallet_events')
    op.drop_table('wallet_events')
    op.drop_index(op.f('ix_trades_session_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_mint'), table_name='trades')
    op.drop_index(op.f('ix_trades_closed_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_tokens_pool_address'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_market_state'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_creator'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_token_state_transitions_mint'), table_name='token_state_transitions')
    op.drop_table('token_state_transitions')
    op.drop_index(op.f('ix_system_events_t'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_signals_t'), table_name='signals')
    op.drop_index(op.f('ix_signals_session_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_outcome'), table_name='signals')
    op.drop_index(op.f('ix_signals_mint'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_signal_outcomes_t'), table_name='signal_outcomes')
    op.drop_index(op.f('ix_signal_outcomes_mint'), table_name='signal_outcomes')
    op.drop_table('signal_outcomes')
    op.drop_index(op.f('ix_scores_t'), table_name='scores')
    op.drop_index(op.f('ix_scores_mint'), table_name='scores')
    op.drop_index(op.f('ix_scores_decision_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_table('runtime_state')
    op.drop_index(op.f('ix_risk_events_t'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_kind'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_research_experiments_name'), table_name='research_experiments')
    op.drop_table('research_experiments')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_session_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_mint'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_position_events_position_id'), table_name='position_events')
    op.drop_table('position_events')
    op.drop_index(op.f('ix_portfolio_snapshots_t'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_session_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_outcome_samples_t'), table_name='outcome_samples')
    op.drop_index(op.f('ix_outcome_samples_strategy_version'), table_name='outcome_samples')
    op.drop_index(op.f('ix_outcome_samples_source'), table_name='outcome_samples')
    op.drop_table('outcome_samples')
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_position_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_mint'), table_name='orders')
    op.drop_index(op.f('ix_orders_decision_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('operator_commands_log')
    op.drop_table('operator_commands')
    op.drop_index('ix_snap_mint_t', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('ix_market_events_t', table_name='market_events')
    op.drop_index(op.f('ix_market_events_slot'), table_name='market_events')
    op.drop_index('ix_market_events_mint_t', table_name='market_events')
    op.drop_table('market_events')
    op.drop_index(op.f('ix_features_t'), table_name='features')
    op.drop_index(op.f('ix_features_mint'), table_name='features')
    op.drop_index(op.f('ix_features_decision_id'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_execution_events_execution_id'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_table('configuration_versions')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_ai_analyses_mint'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_decision_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
