"""Bonding-curve / PumpSwap math vs golden vectors produced by the OFFICIAL Pump SDKs.

tests/fixtures/pump_sdk_golden.json was generated by scripts/gen_pump_golden.js running
@pump-fun/pump-sdk 2.0.0 and @pump-fun/pump-swap-sdk 1.20.0 with the mainnet fee tiers of 2026-09-08.
Every quote must match lamport-for-lamport.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tradingagent.common.types import Side
from tradingagent.pump.amm import PoolState, quote_buy_base_out, quote_buy_quote_in, quote_sell_base_in
from tradingagent.pump.curve import (
    BondingCurveState,
    CurveError,
    initial_state,
    quote_buy_exact_quote_in,
    quote_buy_exact_tokens,
    quote_sell,
)
from tradingagent.pump.fees import FeeSchedule, ceil_div, fee_amount

GOLDEN = json.loads((Path(__file__).parents[1] / "fixtures" / "pump_sdk_golden.json").read_text())
CREATOR = "Coyj3LtKn1BNSgWc9HsGK5SKoGfEoDaymig4wrN6pump"


def _curve(c: dict) -> BondingCurveState:
    return BondingCurveState(
        int(c["vt"]), int(c["vq"]), int(c["rt"]), int(c["rq"]), creator=CREATOR if c["has_creator"] else None
    )


@pytest.mark.parametrize("c", GOLDEN["curve"], ids=lambda c: f"vt{c['vt'][:6]}")
def test_curve_matches_official_sdk(c, sched):
    st = _curve(c)
    assert quote_buy_exact_quote_in(st, int(c["spend"]), sched).amount_out == int(c["tokens_out"])
    assert quote_buy_exact_tokens(st, int(c["tokens_out"]), sched).amount_in == int(c["cost_for_tokens"])
    if c["sell_out"] is not None:
        try:
            assert quote_sell(st, int(c["sell_amount"]), sched).amount_out == int(c["sell_out"])
        except CurveError:
            pytest.skip("sell exceeds real reserves (SDK does not check)")


@pytest.mark.parametrize("a", GOLDEN["amm"], ids=lambda a: f"b{a['base'][:6]}")
def test_amm_matches_official_sdk(a, sched):
    p = PoolState(int(a["base"]), int(a["quote"]), has_coin_creator=a["has_creator"], is_canonical=a["canonical"])
    assert quote_buy_quote_in(p, int(a["quote_in"]), sched).amount_out == int(a["base_out"])
    assert quote_sell_base_in(p, int(a["base_in"]), sched).amount_out == int(a["sell_ui_quote"])
    assert quote_buy_base_out(p, int(a["base_in"]), sched).amount_in == int(a["buy_base_ui_quote"])


def test_fee_helpers():
    assert ceil_div(10, 3) == 4 and ceil_div(9, 3) == 3
    assert fee_amount(1_000_000, 125) == 12_500
    assert fee_amount(1, 1) == 1  # fees round up


def test_fee_tier_selection(cfg):
    s = FeeSchedule.from_rows(cfg.pump.fee_tiers, cfg.pump.flat_fees)
    assert s.tier_for(0).protocol_bps == 93 and s.tier_for(0).creator_bps == 30
    assert s.tier_for(419_999_999_999).creator_bps == 30
    assert s.tier_for(420_000_000_000).creator_bps == 95
    assert s.tier_for(10**18).creator_bps == 5


def test_initial_price_and_mcap():
    st = initial_state()
    assert st.spot_price == pytest.approx(30e9 / 1.073e15)
    assert st.market_cap_lamports == 30_000_000_000 * 10**15 // 1_073_000_000_000_000
    assert st.progress == 0.0


def test_buy_then_sell_round_trip_loses_exactly_fees_and_rounding(sched):
    st = initial_state(creator=CREATOR)
    buy = quote_buy_exact_quote_in(st, 1_000_000_000, sched)
    sell = quote_sell(buy.state_after, buy.amount_out, sched)
    assert sell.amount_out < buy.amount_in
    lost = buy.amount_in - sell.amount_out
    assert lost == pytest.approx(buy.total_fee + sell.total_fee, abs=3)  # reserves return to start
    back = sell.state_after
    assert back.virtual_token_reserves == st.virtual_token_reserves
    assert abs(back.virtual_quote_reserves - st.virtual_quote_reserves) <= 2


def test_price_impact_grows_with_size(sched):
    st = initial_state(creator=CREATOR)
    small = quote_buy_exact_quote_in(st, 100_000_000, sched)
    big = quote_buy_exact_quote_in(st, 10_000_000_000, sched)
    assert 0 < small.price_impact < big.price_impact
    assert big.side is Side.BUY and big.all_in_slippage > big.price_impact  # fees on top of impact


def test_curve_completion_and_cap(sched):
    st = initial_state(creator=CREATOR)
    q = quote_buy_exact_quote_in(st, 200 * 10**9, sched)  # more than the whole curve
    assert q.amount_out == st.real_token_reserves
    assert q.state_after.complete is True
    with pytest.raises(CurveError):
        quote_buy_exact_quote_in(q.state_after, 10**9, sched)


def test_no_creator_means_no_creator_fee(sched):
    with_c = quote_buy_exact_quote_in(initial_state(creator=CREATOR), 10**9, sched)
    without = quote_buy_exact_quote_in(initial_state(creator=None), 10**9, sched)
    assert with_c.creator_fee > 0 and without.creator_fee == 0
    assert without.amount_out > with_c.amount_out


def test_effective_quote_reserves_can_be_negative(sched):
    p = PoolState(base_reserve=10**14, quote_reserve=50 * 10**9, virtual_quote_reserves=-5 * 10**9)
    assert p.effective_quote == 45 * 10**9
    q = quote_sell_base_in(p, 10**12, sched)
    assert q.amount_out > 0
